# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
#permalink:      /:categories/:title/
#permalink:  pretty

# Setup
title:            Tim Dennis
tagline:          'Data Librarian @UCLALibrary'
description:      'Data Librarian @UCLALibrary'
url:              http://jt14den.github.io
baseurl:          /

author:
  name:           'Tim Dennis'
  url:            https://twitter.com/jt14den


paginate:         8

# Custom vars
version:          2.1.0
gems: [jekyll-paginate, jekyll-mentions]

github:
  repo:           https://github.com/jt14den/

twitter_username:     jt14den
github_username:      jt14den
linkedin_username:    jtimdennis
orcid:                0000-0001-6632-3812
