# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Tim Dennis
tagline:          'Data Librarian'
description:      'Data Librarian'
url:              http://jt14den.github.io
baseurl:          ''

author:
  name:           'Tim Dennis'
  url:            https://twitter.com/jt14den

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/jt14den/jt14den.github.com

#Gems
gems: [jekyll-paginate]
paginate: 5
paginate-path: "page:num"

